### ISSUE TITLE
music bug tracker

### ISSUE THREAD

**Issue by calico32** [gamer-gang/gamerbot-classic#3]
soon™

- [x] don't include song being added when doing "approx _ until playing"
- [x] fix music embed bar/timestamps
- [x] `$q rm` bugs
- [x] songs finishing immediately sometimes
- [x] slowness of initial load
- [ ] weird disconnects midway through a track sometimes
- [ ] track ends and the next doesn't start
